spring.application.name=spring_data
# Ejercicio 1 JPA: Configuración de la conexión a la base de datos MySQL
# Credenciales de acceso a la base de datos (configuración por defecto de XAMPP)
spring.datasource.username=root
spring.datasource.password=
# Ruta de conexión (URL) a la base de datos local
# Apunta al puerto 3306 y a la base de datos 'spring_data' previamente creada
spring.datasource.url=jdbc:mysql://localhost:3306/spring_data?serverTimezone=UTC
# Configuración del comportamiento de Hibernate (ORM)
# Estrategia de generación del esquema de la base de datos
# Utilizo 'update' para que Hibernate actualice las tablas según mis clases Java (@Entity)
# sin destruir los datos que ya estén guardados en la base de datos.
spring.jpa.hibernate.ddl-auto=update
# Trazabilidad en consola
# Activo esta opción para poder ver en la consola de IntelliJ las sentencias SQL
# reales (INSERT, SELECT, UPDATE) que Spring Boot está ejecutando por debajo.
spring.jpa.show-sql=true